import { useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { Heart, LogOut, MapPin, Package, Save, ShieldCheck, UserRound } from 'lucide-react';
import { put } from '../services/api';
import { useAuth } from '../store/auth';

export default function Account() {
  const user = useAuth((s)=>s.user); const logout = useAuth((s)=>s.logout); const updateProfile = useAuth((s)=>s.updateProfile);
  const [profile,setProfile]=useState({name:user?.name||'',phone:user?.phone||''});
  const [passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirmPassword:''});
  const [state,setState]=useState({busy:'',message:'',error:''});
  if(!user)return <Navigate to="/login" replace/>;
  async function saveProfile(e){e.preventDefault();setState({busy:'profile',message:'',error:''});try{await updateProfile(profile);setState({busy:'',message:'Profile saved.',error:''});}catch(error){setState({busy:'',message:'',error:error.message});}}
  async function savePassword(e){e.preventDefault();if(passwords.newPassword!==passwords.confirmPassword){setState({busy:'',message:'',error:'New passwords do not match.'});return;}setState({busy:'password',message:'',error:''});try{const result=await put('/account/password',{currentPassword:passwords.currentPassword,newPassword:passwords.newPassword});setPasswords({currentPassword:'',newPassword:'',confirmPassword:''});setState({busy:'',message:result.message,error:''});}catch(error){setState({busy:'',message:'',error:error.message});}}
  return <main className="section"><div className="container narrow"><div className="page-title"><span className="eyebrow">Account</span><h1>Hello, {user.name || 'Customer'}</h1><p>{user.email}</p></div><div className="account-grid"><Link className="account-card" to="/account/orders"><Package/><div><strong>Orders</strong><p>Review purchases, cancellation and return status.</p></div></Link><Link className="account-card" to="/account/wishlist"><Heart/><div><strong>Wishlist</strong><p>Products you saved for later.</p></div></Link><Link className="account-card" to="/account/addresses"><MapPin/><div><strong>Addresses</strong><p>Manage delivery addresses.</p></div></Link><button className="account-card" onClick={logout}><LogOut/><div><strong>Sign out</strong><p>End this session.</p></div></button></div>
  <div className="account-settings-grid"><form className="form-card" onSubmit={saveProfile}><div className="settings-title"><UserRound/><div><h2>Profile</h2><p>Keep delivery contact details up to date.</p></div></div><label><span>Name</span><input required minLength="2" value={profile.name} onChange={(e)=>setProfile({...profile,name:e.target.value})}/></label><label><span>Email</span><input value={user.email} disabled/></label><label><span>Phone</span><input value={profile.phone} onChange={(e)=>setProfile({...profile,phone:e.target.value})}/></label><button className="button secondary" disabled={state.busy==='profile'}><Save size={16}/>{state.busy==='profile'?'Saving…':'Save profile'}</button></form>
  <form className="form-card" onSubmit={savePassword}><div className="settings-title"><ShieldCheck/><div><h2>Password</h2><p>Change the password for this account.</p></div></div><label><span>Current password</span><input type="password" required value={passwords.currentPassword} onChange={(e)=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label><span>New password</span><input type="password" minLength="8" required value={passwords.newPassword} onChange={(e)=>setPasswords({...passwords,newPassword:e.target.value})}/></label><label><span>Confirm new password</span><input type="password" minLength="8" required value={passwords.confirmPassword} onChange={(e)=>setPasswords({...passwords,confirmPassword:e.target.value})}/></label><button className="button secondary" disabled={state.busy==='password'}><ShieldCheck size={16}/>{state.busy==='password'?'Updating…':'Change password'}</button></form></div>
  {state.error&&<div className="alert error block-gap">{state.error}</div>}{state.message&&<div className="alert success block-gap">{state.message}</div>}</div></main>;
}
