import { useEffect, useState } from 'react';
import { Navigate, useOutletContext } from 'react-router-dom';
import { Edit3, Plus, Trash2 } from 'lucide-react';
import { get, post, put, remove } from '../services/api';
import { useAuth } from '../store/auth';
import Loading from '../components/Loading';
import EmptyState from '../components/EmptyState';

const empty={label:'Home',fullName:'',phone:'',line1:'',line2:'',city:'',state:'',postalCode:'',country:'',isDefault:false};
export default function Addresses(){
 const user=useAuth((s)=>s.user);const{config}=useOutletContext();const[items,setItems]=useState(null);const[editing,setEditing]=useState(null);const[form,setForm]=useState(empty);const[open,setOpen]=useState(false);const[error,setError]=useState('');
 async function load(){setItems(await get('/account/addresses'));}useEffect(()=>{if(user)load().catch(()=>setItems([]));},[user]);
 if(!user)return <Navigate to="/login" replace/>;if(!items)return <Loading/>;
 function start(item=null){setEditing(item);setForm(item?{...empty,...item}:{...empty,country:config?.commerceSettings?.defaultCountry||''});setOpen(true);setError('');}
 async function save(e){e.preventDefault();try{editing?await put(`/account/addresses/${editing.id}`,form):await post('/account/addresses',form);setOpen(false);await load();}catch(e){setError(e.message)}}
 async function del(id){if(confirm('Remove this address?')){await remove(`/account/addresses/${id}`);await load();}}
 return <main className="section"><div className="container narrow"><div className="page-title row-between"><div><span className="eyebrow">Account</span><h1>Addresses</h1></div><button className="button primary" onClick={()=>start()}><Plus size={17}/> Add address</button></div>{items.length?<div className="address-grid">{items.map((item)=><article className="admin-panel" key={item.id}><div className="row-between"><strong>{item.label||'Address'}{item.isDefault?' · Default':''}</strong><div className="row-actions"><button className="icon-button" onClick={()=>start(item)}><Edit3 size={16}/></button><button className="icon-button danger" onClick={()=>del(item.id)}><Trash2 size={16}/></button></div></div><p>{item.fullName}<br/>{item.line1}{item.line2?<><br/>{item.line2}</>:null}<br/>{item.city}, {item.state} {item.postalCode}<br/>{item.country}<br/>{item.phone}</p></article>)}</div>:<EmptyState title="No saved addresses" text="Add an address to make future checkout faster."/>}
 {open&&<div className="modal-backdrop" onMouseDown={(e)=>e.currentTarget===e.target&&setOpen(false)}><form className="modal-card wide" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">Address</span><h2>{editing?'Edit address':'Add address'}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label><span>Label</span><input value={form.label||''} onChange={(e)=>setForm({...form,label:e.target.value})}/></label><label><span>Full name *</span><input required value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})}/></label><label><span>Phone *</span><input required value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label><span>Country *</span><input required value={form.country} onChange={(e)=>setForm({...form,country:e.target.value})}/></label><label className="span-2"><span>Address *</span><input required value={form.line1} onChange={(e)=>setForm({...form,line1:e.target.value})}/></label><label className="span-2"><span>Address line 2</span><input value={form.line2||''} onChange={(e)=>setForm({...form,line2:e.target.value})}/></label><label><span>City *</span><input required value={form.city} onChange={(e)=>setForm({...form,city:e.target.value})}/></label><label><span>State *</span><input required value={form.state} onChange={(e)=>setForm({...form,state:e.target.value})}/></label><label><span>Postal code *</span><input required value={form.postalCode} onChange={(e)=>setForm({...form,postalCode:e.target.value})}/></label></div><label className="check-card"><input type="checkbox" checked={form.isDefault} onChange={(e)=>setForm({...form,isDefault:e.target.checked})}/><span><strong>Default address</strong><small>Use this first during checkout</small></span></label>{error&&<div className="alert error">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save address</button></div></form></div>}</div></main>;
}
