import { useEffect, useMemo, useState } from 'react';
import { Link, useOutletContext, useParams } from 'react-router-dom';
import { Check, Heart, Minus, Plus, ShoppingBag } from 'lucide-react';
import { get, post } from '../services/api';
import { useCart } from '../store/cart';
import { useAuth } from '../store/auth';
import Loading from '../components/Loading';
import ProductCard from '../components/ProductCard';
import { absoluteUrl, breadcrumbSchema, useSeo } from '../utils/seo';
import { formatMoney } from '../utils/money';

const RECENT_KEY = 'store-recently-viewed-v1';
export default function Product() {
  const { slug } = useParams(); const { config } = useOutletContext(); const text = config?.storefrontText || {}; const user = useAuth((s) => s.user);
  const [product,setProduct]=useState(null),[selectedImage,setSelectedImage]=useState(0),[variantId,setVariantId]=useState(''),[quantity,setQuantity]=useState(1),[error,setError]=useState(''),[notice,setNotice]=useState(''),[related,setRelated]=useState([]),[recent,setRecent]=useState([]);
  const [review,setReview]=useState({rating:5,title:'',body:''}); const add=useCart((s)=>s.add);
  useEffect(()=>{get(`/storefront/products/${slug}`).then(async(p)=>{setProduct(p);setVariantId(p.variants?.[0]?.id||'');setSelectedImage(0);const saved=JSON.parse(localStorage.getItem(RECENT_KEY)||'[]').filter((x)=>x.slug!==p.slug);setRecent(saved.slice(0,4));localStorage.setItem(RECENT_KEY,JSON.stringify([{id:p.id,name:p.name,slug:p.slug,price:p.price,compareAtPrice:p.compareAtPrice,images:p.images?.slice(0,1)||[],variants:p.variants?.map(v=>({id:v.id,price:v.price,compareAtPrice:v.compareAtPrice,stock:v.stock,isActive:v.isActive}))||[],stock:p.stock,category:p.category,brand:p.brand},...saved].slice(0,8)));if(p.category?.slug){const r=await get(`/storefront/products?category=${encodeURIComponent(p.category.slug)}&limit=5`);setRelated((r.items||[]).filter(x=>x.id!==p.id).slice(0,4));}}).catch(e=>setError(e.message));},[slug]);
  const variant=useMemo(()=>product?.variants?.find(v=>v.id===variantId)||null,[product,variantId]);
  useEffect(()=>{if(!product||!variant?.imageUrl)return;const idx=(product.images||[]).findIndex(img=>img.url===variant.imageUrl);setSelectedImage(idx);},[variantId,product,variant]);
  const totalStock=product?.variants?.length?product.variants.reduce((s,i)=>s+Number(i.stock||0),0):Number(product?.stock||0); const schemaPrice=Number(variant?.price??product?.variants?.[0]?.price??product?.price??0);
  const productSchema=product?{'@context':'https://schema.org','@graph':[breadcrumbSchema([{name:'Home',path:'/'},{name:'Catalog',path:'/shop'},...(product.category?[{name:product.category.name,path:`/category/${product.category.slug}`}]:[]),{name:product.name,path:`/product/${product.slug}`}]),{'@type':'Product',name:product.name,description:product.shortDescription||product.description||'',image:product.images?.map(i=>absoluteUrl(i.url))||[],sku:variant?.sku||product.sku||undefined,brand:product.brand?{'@type':'Brand',name:product.brand.name}:undefined,offers:{'@type':'Offer',priceCurrency:config?.currency||'INR',price:String(schemaPrice),availability:totalStock>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:absoluteUrl(`/product/${product.slug}`)}}]}:undefined;
  useSeo({title:product?.metaTitle||product?.name,description:product?.metaDescription||product?.shortDescription,canonical:product?.canonicalUrl,image:product?.ogImageUrl||product?.images?.[0]?.url,noIndex:product?.noIndex,schema:productSchema});
  if(error)return <main className="section"><div className="container"><div className="alert error">{error}</div></div></main>; if(!product)return <Loading label="Loading product…"/>;
  const images=product.images||[]; const price=Number(variant?.price??product.price); const compare=Number(variant?.compareAtPrice??product.compareAtPrice??0); const stock=Number(variant?.stock??product.stock);
  async function submitReview(e){e.preventDefault();if(!user){setNotice('Sign in to write a review.');return;}try{const r=await post(`/products/${product.id}/reviews`,{...review,rating:Number(review.rating)});setNotice(r.message||'Review submitted for moderation.');setReview({rating:5,title:'',body:''});}catch(e){setNotice(e.message)}}
  async function wishlist(){if(!user){setNotice('Sign in to save products to your wishlist.');return;}try{await post(`/account/wishlist/${product.id}`,{});setNotice('Saved to your wishlist.');}catch(e){setNotice(e.message)}}
  return <main className="section"><div className="container"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><Link to="/shop">Catalog</Link>{product.category&&<><span>/</span><Link to={`/category/${product.category.slug}`}>{product.category.name}</Link></>}<span>/</span><b>{product.name}</b></div><div className="product-detail"><div className="gallery"><div className="main-image">{images[selectedImage]?.url?<img src={images[selectedImage].url} alt={images[selectedImage].altText||product.name}/>:variant?.imageUrl?<img src={variant.imageUrl} alt={`${product.name} ${variant.title}`}/>:<div className="image-placeholder">No image</div>}</div>{images.length>1&&<div className="thumb-row">{images.map((img,i)=><button className={i===selectedImage?'active':''} key={img.id} onClick={()=>setSelectedImage(i)}><img src={img.url} alt={img.altText||product.name}/></button>)}</div>}</div><div className="product-copy"><span className="eyebrow">{product.brand?.name||product.category?.name||'Product'}</span><h1>{product.name}</h1>{product.shortDescription&&<p className="lead">{product.shortDescription}</p>}<div className="detail-price"><strong>{formatMoney(price,config)}</strong>{compare>price&&<del>{formatMoney(compare,config)}</del>}</div><div className="stock-line"><Check size={17}/>{stock>0?`${stock} available`:'Out of stock'}</div>{product.variants?.length>0&&<label className="option-field"><span>Choose option</span><select value={variantId} onChange={e=>{setVariantId(e.target.value);setQuantity(1);}}>{product.variants.filter(v=>v.isActive).map(v=><option key={v.id} value={v.id}>{v.title} — {formatMoney(v.price,config)}{Number(v.compareAtPrice)>Number(v.price)?' · Sale':''}</option>)}</select></label>}<div className="buy-row"><div className="quantity"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}><Minus size={16}/></button><span>{quantity}</span><button onClick={()=>setQuantity(Math.min(Math.max(stock,1),quantity+1,99))}><Plus size={16}/></button></div><button className="button primary grow" disabled={stock<1} onClick={()=>add(product,variant,Math.min(quantity,stock))}><ShoppingBag size={18}/> {text.addToCartLabel||'Add to cart'}</button><button className="button secondary" type="button" onClick={wishlist} aria-label="Save to wishlist"><Heart size={18}/></button></div>{notice&&<div className="notice-line">{notice}</div>}<div className="detail-notes"><div><strong>SKU</strong><span>{variant?.sku||product.sku||'—'}</span></div><div><strong>Category</strong><span>{product.category?.name||'—'}</span></div></div></div></div><div className="product-content"><h2>Details</h2><p>{product.description||product.shortDescription||'Product details can be added from the CMS.'}</p></div>
  {related.length>0&&<section className="section-tight"><div className="section-head"><div><h2>You may also like</h2><p>Related products from the same category.</p></div></div><div className="dynamic-grid">{related.map(p=><ProductCard product={p} key={p.id}/>)}</div></section>}
  {recent.length>0&&<section className="section-tight"><div className="section-head"><div><h2>Recently viewed</h2><p>Continue where you left off.</p></div></div><div className="dynamic-grid">{recent.map(p=><ProductCard product={p} key={p.slug}/>)}</div></section>}
  <section className="section-tight"><div className="section-head"><div><h2>Customer reviews</h2><p>{product.reviews?.length||0} published review{product.reviews?.length===1?'':'s'}</p></div></div>{product.reviews?.length>0&&<div className="review-grid">{product.reviews.map(item=><article className="trust-card" key={item.id}><strong>{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</strong><p>{item.body||item.title||'Customer review'}</p><small>{item.user?.name||'Customer'}{item.isVerified?' · Verified purchase':''}</small></article>)}</div>}{user?<form className="form-card review-form" onSubmit={submitReview}><h3>Write a review</h3><div className="two-fields"><label><span>Rating</span><select value={review.rating} onChange={e=>setReview({...review,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(r=><option value={r} key={r}>{r} / 5</option>)}</select></label><label><span>Title</span><input value={review.title} onChange={e=>setReview({...review,title:e.target.value})}/></label></div><label><span>Review</span><textarea rows="4" value={review.body} onChange={e=>setReview({...review,body:e.target.value})}/></label><button className="button secondary">Submit review</button></form>:<p className="muted"><Link className="text-link" to="/login">Sign in</Link> to write a review.</p>}</section></div></main>;
}
