import { useEffect, useState } from 'react';
import { Link, useOutletContext, useSearchParams } from 'react-router-dom';
import { post, get } from '../services/api';
import { formatMoney } from '../utils/money';
import { useAuth } from '../store/auth';

const milestones=['PENDING','CONFIRMED','PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED'];
export default function TrackOrder(){
  const[params]=useSearchParams();const{config}=useOutletContext();const user=useAuth((s)=>s.user);
  const[values,setValues]=useState({order:params.get('order')||'',email:params.get('email')||user?.email||''});const[order,setOrder]=useState(null);const[error,setError]=useState('');const[request,setRequest]=useState({open:false,action:'CANCEL',reason:'',busy:false,message:''});
  async function lookup(){if(!values.order||!values.email)return;setError('');try{setOrder(await get(`/orders/${encodeURIComponent(values.order)}?email=${encodeURIComponent(values.email)}`));}catch(e){setOrder(null);setError(e.message)}}
  useEffect(()=>{if(values.order&&values.email)lookup();},[]);
  async function submit(e){e.preventDefault();lookup();}
  async function sendRequest(e){e.preventDefault();setRequest((r)=>({...r,busy:true,message:''}));try{const result=await post(`/orders/${encodeURIComponent(order.orderNumber)}/request`,{email:values.email,action:request.action,reason:request.reason});setOrder(result.order);setRequest({open:false,action:'CANCEL',reason:'',busy:false,message:result.message});}catch(e){setRequest((r)=>({...r,busy:false,message:e.message}));}}
  const canCancel=order&&['PENDING','CONFIRMED','PROCESSING'].includes(order.status);const canReturn=order?.status==='DELIVERED';
  return <main className="section"><div className="container narrow"><div className="page-title"><span className="eyebrow">Delivery</span><h1>Track your order</h1><p>Enter the order number and checkout email.</p></div><form className="form-card" onSubmit={submit}><div className="form-grid"><label><span>Order number</span><input required value={values.order} onChange={(e)=>setValues({...values,order:e.target.value})}/></label><label><span>Email</span><input type="email" required value={values.email} onChange={(e)=>setValues({...values,email:e.target.value})}/></label></div>{error&&<div className="alert error">{error}</div>}<button className="button primary">Track order</button></form>{order&&<div className="tracking-card"><div className="row-between"><div><span className="eyebrow">{order.orderNumber}</span><h2>{order.status.replaceAll('_',' ')}</h2></div><strong>{formatMoney(order.total,config)}</strong></div>{milestones.includes(order.status)&&<div className="tracking-line">{['Confirmed','Processing','Shipped','Delivered'].map((label,index)=>{const statusIndex=milestones.indexOf(order.status);const step=[1,2,4,6][index];return <span className={statusIndex>=step?'done':''} key={label}>{label}</span>;})}</div>}{['CANCEL_REQUESTED','RETURN_REQUESTED'].includes(order.status)&&<div className="alert warning">Your {order.status==='CANCEL_REQUESTED'?'cancellation':'return'} request is waiting for the store team.</div>}{order.trackingNumber&&<p>Tracking: <strong>{order.trackingNumber}</strong>{order.trackingUrl&&<> · <a className="text-link" href={order.trackingUrl} target="_blank" rel="noreferrer">Carrier link</a></>}</p>}<div className="summary-lines">{order.items?.map((item)=><div className="summary-line" key={item.id}><span>{item.productName}{item.variantName?` · ${item.variantName}`:''} × {item.quantity}</span><strong>{formatMoney(item.total,config)}</strong></div>)}</div>{(canCancel||canReturn)&&<div className="order-request-actions">{canCancel&&<button className="button secondary small" onClick={()=>setRequest({open:true,action:'CANCEL',reason:'',busy:false,message:''})}>Request cancellation</button>}{canReturn&&<button className="button secondary small" onClick={()=>setRequest({open:true,action:'RETURN',reason:'',busy:false,message:''})}>Request return</button>}</div>}{request.message&&<div className={request.open?'alert error':'alert success'}>{request.message}</div>}</div>}
  {request.open&&<form className="form-card block-gap" onSubmit={sendRequest}><h2>{request.action==='CANCEL'?'Cancellation request':'Return request'}</h2><p className="muted">The store team will review this request. Add a reason to help them process it.</p><label><span>Reason</span><textarea rows="4" maxLength="1000" value={request.reason} onChange={(e)=>setRequest({...request,reason:e.target.value})}/></label>{request.message&&<div className="alert error">{request.message}</div>}<div className="row-actions"><button type="button" className="button secondary" onClick={()=>setRequest({open:false,action:'CANCEL',reason:'',busy:false,message:''})}>Close</button><button className="button primary" disabled={request.busy}>{request.busy?'Submitting…':'Submit request'}</button></div></form>}
  <p className="muted block-gap"><Link className="text-link" to="/account/orders">View account orders</Link></p></div></main>;
}
