import { useEffect, useState } from 'react';
import { Edit3, Plus, Trash2 } from 'lucide-react';
import { get, post, put, remove } from '../../services/api';
import { AdminPageHead, HelpNote } from '../AdminLayout';
import ImageUploadButton from '../../components/ImageUploadButton';

const tabs = [
  { key:'categories', label:'Categories', singular:'category', help:'Organize products in a hierarchy. Works for any business type.' },
  { key:'collections', label:'Collections', singular:'collection', help:'Create flexible groups such as New Arrivals, Seasonal, Premium or any name you choose.' },
  { key:'brands', label:'Brands', singular:'brand', help:'Brands are optional and can be hidden when your store does not need them.' }
];
const empty = { name:'', slug:'', description:'', imageUrl:'', logoUrl:'', parentId:'', metaTitle:'', metaDescription:'', noIndex:false, sortOrder:0, isActive:true };

export default function Catalog() {
  const [tab,setTab]=useState(tabs[0]); const [items,setItems]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [open,setOpen]=useState(false); const [error,setError]=useState('');
  async function load(){setItems(await get(`/admin/${tab.key}`));}
  useEffect(()=>{load();},[tab.key]);
  function start(item=null){setEditing(item);setForm(item?{...empty,...item,parentId:item.parentId||''}:{...empty});setOpen(true);setError('');}
  async function save(e){e.preventDefault();try{const payload={...form,parentId:tab.key==='categories'?(form.parentId||null):undefined,sortOrder:Number(form.sortOrder||0)}; if(tab.key!=='categories')delete payload.parentId; if(tab.key==='brands'){delete payload.imageUrl;} else {delete payload.logoUrl;} editing?await put(`/admin/${tab.key}/${editing.id}`,payload):await post(`/admin/${tab.key}`,payload);setOpen(false);load();}catch(e){setError(e.message)}}
  async function del(item){if(confirm(`Delete ${item.name}?`)){try{await remove(`/admin/${tab.key}/${item.id}`);load();}catch(e){alert(e.message)}}}
  return <><AdminPageHead eyebrow="Catalog setup" title="Organize your catalog" description="Use your own words. Nothing here is tied to fruit, shoes, electronics or any other industry." action={<button className="button primary" onClick={()=>start()}><Plus size={17}/> Add {tab.singular}</button>}/><div className="segmented">{tabs.map((t)=><button className={t.key===tab.key?'active':''} key={t.key} onClick={()=>setTab(t)}>{t.label}</button>)}</div><HelpNote>{tab.help}</HelpNote><div className="admin-panel"><div className="panel-head"><div><h2>{tab.label}</h2><p>{items.length} configured</p></div></div>{items.length?<div className="simple-list">{items.map((item)=><div className="simple-row" key={item.id}><div className="avatar-square">{(tab.key==='brands'?item.logoUrl:item.imageUrl)?<img src={tab.key==='brands'?item.logoUrl:item.imageUrl} alt=""/>:item.name.slice(0,1)}</div><div className="grow"><strong>{item.name}</strong><small>/{item.slug}{item.parentId?' · nested category':''}</small></div><span className={item.isActive?'status-pill published':'status-pill draft'}>{item.isActive?'Active':'Hidden'}</span><button className="icon-button" onClick={()=>start(item)}><Edit3 size={16}/></button><button className="icon-button danger" onClick={()=>del(item)}><Trash2 size={16}/></button></div>)}</div>:<div className="soft-panel">No {tab.label.toLowerCase()} yet.</div>}</div>
    {open&&<div className="modal-backdrop" onMouseDown={(e)=>e.currentTarget===e.target&&setOpen(false)}><form className="modal-card" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{editing?'Edit':'Add'} {tab.singular}</span><h2>{editing?editing.name:`New ${tab.singular}`}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label><span>Name *</span><input required autoFocus value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder={`Example ${tab.singular} name`}/></label><label><span>URL slug</span><input value={form.slug||''} onChange={(e)=>setForm({...form,slug:e.target.value})} placeholder="Auto-generated when left blank"/></label><label><span>Description</span><textarea rows="3" value={form.description||''} onChange={(e)=>setForm({...form,description:e.target.value})}/></label>{tab.key==='categories'&&<label><span>Parent category (optional)</span><select value={form.parentId} onChange={(e)=>setForm({...form,parentId:e.target.value})}><option value="">Top level</option>{items.filter((x)=>x.id!==editing?.id).map((x)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<div className="admin-panel inset-panel"><strong>Search visibility</strong><label><span>SEO title</span><input value={form.metaTitle||''} onChange={(e)=>setForm({...form,metaTitle:e.target.value})} placeholder="Optional search title"/></label><label><span>Meta description</span><textarea rows="2" value={form.metaDescription||''} onChange={(e)=>setForm({...form,metaDescription:e.target.value})}/></label><label className="check-card"><input type="checkbox" checked={Boolean(form.noIndex)} onChange={(e)=>setForm({...form,noIndex:e.target.checked})}/><span><strong>Hide from search engines</strong><small>Useful for temporary categories.</small></span></label></div><label><span>{tab.key==='brands'?'Logo':'Image'}</span><div className="inline-field"><input value={tab.key==='brands'?(form.logoUrl||''):(form.imageUrl||'')} onChange={(e)=>setForm({...form,[tab.key==='brands'?'logoUrl':'imageUrl']:e.target.value})} placeholder="Upload or paste an image URL"/><ImageUploadButton onUploaded={(url)=>setForm({...form,[tab.key==='brands'?'logoUrl':'imageUrl']:url})}/></div></label><div className="two-fields"><label><span>Display order</span><input type="number" value={form.sortOrder} onChange={(e)=>setForm({...form,sortOrder:e.target.value})}/></label><label className="check-card"><input type="checkbox" checked={form.isActive} onChange={(e)=>setForm({...form,isActive:e.target.checked})}/><span><strong>Visible</strong><small>Show this on the storefront</small></span></label></div>{error&&<div className="alert error">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save</button></div></form></div>}
  </>;
}
