import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Edit3, Eye, EyeOff, Plus, Trash2 } from 'lucide-react';
import { get, post, put, remove } from '../../services/api';
import { AdminPageHead, HelpNote } from '../AdminLayout';
import ImageUploadButton from '../../components/ImageUploadButton';

const types = [
  ['HERO','Hero banner'],['CATEGORY_GRID','Category grid'],['PRODUCT_GRID','Product grid'],['COLLECTION_GRID','Collection grid'],['BRAND_GRID','Brand grid'],['BLOG_GRID','Blog articles'],['BANNER','Promotional banner'],['TEXT','Text section'],['TRUST','Trust / service cards'],['FAQ','FAQ section']
];
const defaultLayout={width:'BOXED',paddingY:58,radius:20,desktopHeight:0,mobileHeight:0,imageFit:'cover',textAlign:'left',columns:4,mobileColumns:2,gap:15,background:'',textColor:''};
const blank={type:'TEXT',title:'',subtitle:'',sortOrder:0,isActive:true,content:{layout:{...defaultLayout}}};

export default function Homepage(){
  const[items,setItems]=useState([]);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState(blank);const[error,setError]=useState('');const[catalog,setCatalog]=useState({categories:[],collections:[],brands:[]});
  async function load(){setItems(await get('/admin/home-sections'));}useEffect(()=>{load();Promise.all([get('/storefront/categories'),get('/storefront/collections'),get('/storefront/brands')]).then(([categories,collections,brands])=>setCatalog({categories,collections,brands})).catch(()=>{});},[]);
  function start(item=null){const content=item?.content||{};setEditing(item);setForm(item?{...blank,...item,content:{...content,layout:{...defaultLayout,...(content.layout||{})}}}:{...blank,content:{layout:{...defaultLayout}},sortOrder:items.length+1});setOpen(true);setError('');}
  async function save(e){e.preventDefault();try{editing?await put(`/admin/home-sections/${editing.id}`,form):await post('/admin/home-sections',form);setOpen(false);load();}catch(e){setError(e.message)}}
  async function update(item,patch){await put(`/admin/home-sections/${item.id}`,{...item,...patch});load();}
  async function move(item,direction){const sorted=[...items].sort((a,b)=>a.sortOrder-b.sortOrder);const index=sorted.findIndex((x)=>x.id===item.id);const target=sorted[index+direction];if(!target)return;await Promise.all([put(`/admin/home-sections/${item.id}`,{...item,sortOrder:target.sortOrder}),put(`/admin/home-sections/${target.id}`,{...target,sortOrder:item.sortOrder})]);load();}
  async function del(item){if(confirm(`Remove section “${item.title||item.type}”?`)){await remove(`/admin/home-sections/${item.id}`);load();}}
  function content(key,value){setForm((current)=>({...current,content:{...(current.content||{}),[key]:value}}));}
  function layout(key,value){setForm((current)=>({...current,content:{...(current.content||{}),layout:{...defaultLayout,...(current.content?.layout||{}),[key]:value}}}));}
  const l={...defaultLayout,...(form.content?.layout||{})};
  return <><AdminPageHead eyebrow="Store design" title="Homepage builder" description="Arrange and resize reusable sections. Merchants control wording, images, spacing, width and grid density without changing React or CSS." action={<button className="button primary" onClick={()=>start()}><Plus size={17}/> Add section</button>}/><HelpNote title="No fixed banner size">Every section has its own width, spacing, height, image-fit and responsive grid settings. Use 0 for automatic height so content decides the size.</HelpNote><div className="section-list">{items.map((item,index)=><div className="section-row-card" key={item.id}><div className="section-order"><button disabled={index===0} onClick={()=>move(item,-1)}><ArrowUp size={15}/></button><span>{index+1}</span><button disabled={index===items.length-1} onClick={()=>move(item,1)}><ArrowDown size={15}/></button></div><div className="section-icon">{item.type.slice(0,1)}</div><div className="grow"><strong>{item.title||types.find((t)=>t[0]===item.type)?.[1]||item.type}</strong><small>{types.find((t)=>t[0]===item.type)?.[1]} · {item.content?.layout?.width||'BOXED'}{item.subtitle?` · ${item.subtitle}`:''}</small></div><button className="visibility" onClick={()=>update(item,{isActive:!item.isActive})}>{item.isActive?<><Eye size={16}/> Visible</>:<><EyeOff size={16}/> Hidden</>}</button><button className="icon-button" onClick={()=>start(item)}><Edit3 size={16}/></button><button className="icon-button danger" onClick={()=>del(item)}><Trash2 size={16}/></button></div>)}</div>
  {open&&<div className="modal-backdrop" onMouseDown={(e)=>e.currentTarget===e.target&&setOpen(false)}><form className="modal-card wide" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">Homepage section</span><h2>{editing?'Edit section':'Add section'}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label><span>Section type</span><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Heading</span><input value={form.title||''} onChange={(e)=>setForm({...form,title:e.target.value})} placeholder="Write a clear heading in any language"/></label><label><span>Supporting text</span><textarea rows="2" value={form.subtitle||''} onChange={(e)=>setForm({...form,subtitle:e.target.value})}/></label>
  {['HERO','BANNER','TEXT'].includes(form.type)&&<><label><span>Small label above heading</span><input value={form.content?.eyebrow||''} onChange={(e)=>content('eyebrow',e.target.value)}/></label><div className="two-fields"><label><span>Button text</span><input value={form.content?.ctaLabel||''} onChange={(e)=>content('ctaLabel',e.target.value)}/></label><label><span>Button link</span><input value={form.content?.ctaUrl||''} onChange={(e)=>content('ctaUrl',e.target.value)} placeholder="/shop or any CMS route"/></label></div><label><span>{form.type==='HERO'?'Hero image':'Section image'}</span><div className="inline-field"><input value={form.content?.imageUrl||''} onChange={(e)=>content('imageUrl',e.target.value)} placeholder="Upload or paste an image URL"/><ImageUploadButton onUploaded={(url)=>content('imageUrl',url)}/></div></label><label><span>Image alt text</span><input value={form.content?.imageAlt||''} onChange={(e)=>content('imageAlt',e.target.value)} placeholder="Describe the image for accessibility and SEO"/></label></>}
  {['CATEGORY_GRID','COLLECTION_GRID','BRAND_GRID','PRODUCT_GRID','BLOG_GRID','FAQ'].includes(form.type)&&<label><span>Maximum items</span><input type="number" min="1" max="48" value={form.content?.limit||8} onChange={(e)=>content('limit',Number(e.target.value))}/></label>}
  {form.type==='PRODUCT_GRID'&&<><label><span>Product source</span><select value={form.content?.source||'FEATURED'} onChange={(e)=>content('source',e.target.value)}><option value="FEATURED">Featured products</option><option value="LATEST">Newest products</option><option value="CATEGORY">A category</option><option value="COLLECTION">A collection</option><option value="BRAND">A brand</option></select></label>{form.content?.source==='CATEGORY'&&<label><span>Category</span><select value={form.content?.sourceValue||''} onChange={(e)=>content('sourceValue',e.target.value)}><option value="">Choose category</option>{catalog.categories.map((x)=><option key={x.id} value={x.slug}>{x.name}</option>)}</select></label>}{form.content?.source==='COLLECTION'&&<label><span>Collection</span><select value={form.content?.sourceValue||''} onChange={(e)=>content('sourceValue',e.target.value)}><option value="">Choose collection</option>{catalog.collections.map((x)=><option key={x.id} value={x.slug}>{x.name}</option>)}</select></label>}{form.content?.source==='BRAND'&&<label><span>Brand</span><select value={form.content?.sourceValue||''} onChange={(e)=>content('sourceValue',e.target.value)}><option value="">Choose brand</option>{catalog.brands.map((x)=><option key={x.id} value={x.slug}>{x.name}</option>)}</select></label>}</>}
  {form.type==='TRUST'&&<div><span className="field-label">Service cards</span>{(form.content?.items||[]).map((x,i)=><div className="inline-card" key={i}><input value={x.title} placeholder="Title" onChange={(e)=>content('items',form.content.items.map((it,n)=>n===i?{...it,title:e.target.value}:it))}/><input value={x.text} placeholder="Short explanation" onChange={(e)=>content('items',form.content.items.map((it,n)=>n===i?{...it,text:e.target.value}:it))}/><button type="button" onClick={()=>content('items',form.content.items.filter((_,n)=>n!==i))}>×</button></div>)}<button type="button" className="button secondary small" onClick={()=>content('items',[...(form.content?.items||[]),{title:'',text:''}])}>+ Add card</button></div>}
  <div className="builder-divider"><strong>Layout & size</strong><small>These settings are per section and responsive.</small></div><div className="three-fields"><label><span>Width</span><select value={l.width} onChange={(e)=>layout('width',e.target.value)}><option value="BOXED">Boxed / container</option><option value="FULL">Full browser width</option><option value="NARROW">Narrow content</option></select></label><label><span>Text alignment</span><select value={l.textAlign} onChange={(e)=>layout('textAlign',e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label><span>Image fit</span><select value={l.imageFit} onChange={(e)=>layout('imageFit',e.target.value)}><option value="cover">Cover</option><option value="contain">Contain</option></select></label></div><div className="three-fields"><label><span>Vertical spacing (px)</span><input type="number" min="0" max="160" value={l.paddingY} onChange={(e)=>layout('paddingY',Number(e.target.value))}/></label><label><span>Corner radius (px)</span><input type="number" min="0" max="60" value={l.radius} onChange={(e)=>layout('radius',Number(e.target.value))}/></label><label><span>Grid gap (px)</span><input type="number" min="0" max="60" value={l.gap} onChange={(e)=>layout('gap',Number(e.target.value))}/></label></div><div className="three-fields"><label><span>Desktop min height (px)</span><input type="number" min="0" max="1000" value={l.desktopHeight} onChange={(e)=>layout('desktopHeight',Number(e.target.value))}/></label><label><span>Mobile min height (px)</span><input type="number" min="0" max="1000" value={l.mobileHeight} onChange={(e)=>layout('mobileHeight',Number(e.target.value))}/></label><label><span>Desktop columns</span><input type="number" min="1" max="6" value={l.columns} onChange={(e)=>layout('columns',Number(e.target.value))}/></label></div><div className="three-fields"><label><span>Mobile columns</span><input type="number" min="1" max="2" value={l.mobileColumns} onChange={(e)=>layout('mobileColumns',Number(e.target.value))}/></label><label><span>Background color</span><input value={l.background||''} placeholder="Optional #ffffff" onChange={(e)=>layout('background',e.target.value)}/></label><label><span>Text color</span><input value={l.textColor||''} placeholder="Optional #1c2320" onChange={(e)=>layout('textColor',e.target.value)}/></label></div>
  <div className="two-fields"><label><span>Display order</span><input type="number" value={form.sortOrder} onChange={(e)=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><label className="check-card"><input type="checkbox" checked={form.isActive} onChange={(e)=>setForm({...form,isActive:e.target.checked})}/><span><strong>Visible</strong><small>Show this section now</small></span></label></div>{error&&<div className="alert error">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save section</button></div></form></div>}</>;
}
