import { useEffect, useState } from 'react';
import { GripVertical, Plus, Trash2 } from 'lucide-react';
import { get, put } from '../../services/api';
import { AdminPageHead, HelpNote } from '../AdminLayout';

export default function Navigation(){
 const[key,setKey]=useState('header');const[menu,setMenu]=useState({title:'',items:[]});const[state,setState]=useState({saving:false,message:'',error:''});
 useEffect(()=>{get(`/admin/navigation/${key}`).then(setMenu)},[key]);
 function update(i,name,value){setMenu({...menu,items:menu.items.map((x,n)=>n===i?{...x,[name]:value}:x)})}
 async function save(){setState({saving:true,message:'',error:''});try{const data=await put(`/admin/navigation/${key}`,{title:menu.title,items:menu.items.map((x,i)=>({...x,sortOrder:i}))});setMenu(data);setState({saving:false,message:'Navigation saved.',error:''});}catch(e){setState({saving:false,message:'',error:e.message})}}
 return <><AdminPageHead eyebrow="Navigation" title="Store menus" description="Choose the links customers see. Use your own labels and link them to products, content pages, forms or any internal route." action={<button className="button primary" onClick={save} disabled={state.saving}>{state.saving?'Saving…':'Save menu'}</button>}/><div className="segmented"><button className={key==='header'?'active':''} onClick={()=>setKey('header')}>Header menu</button><button className={key==='footer'?'active':''} onClick={()=>setKey('footer')}>Footer menu</button></div><HelpNote>Labels can be written in English, Tamil, Hindi or any other Unicode language. A shop owner changes them here; no React file has to be edited.</HelpNote><div className="admin-panel"><label><span>Menu heading</span><input value={menu.title||''} onChange={(e)=>setMenu({...menu,title:e.target.value})} placeholder="Example: Information"/></label><div className="panel-head"><div><h2>{key==='header'?'Main navigation':'Footer links'}</h2><p>Items appear in this order.</p></div><button className="button secondary small" onClick={()=>setMenu({...menu,items:[...menu.items,{label:'New link',target:'/shop',isActive:true}]})}><Plus size={15}/> Add link</button></div><div className="nav-builder">{menu.items.map((item,index)=><div className="nav-builder-row" key={item.id||index}><GripVertical size={17}/><input value={item.label||''} onChange={(e)=>update(index,'label',e.target.value)} placeholder="Menu label"/><input value={item.target||''} onChange={(e)=>update(index,'target',e.target.value)} placeholder="/shop or /page/about"/><label className="check-line"><input type="checkbox" checked={item.isActive!==false} onChange={(e)=>update(index,'isActive',e.target.checked)}/>Visible</label><button className="icon-button danger" onClick={()=>setMenu({...menu,items:menu.items.filter((_,i)=>i!==index)})}><Trash2 size={15}/></button></div>)}</div>{state.error&&<div className="alert error">{state.error}</div>}{state.message&&<div className="alert success">{state.message}</div>}</div></>;
}
