import { useEffect, useMemo, useState } from 'react';
import { Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import { get, post, put, remove } from '../../services/api';
import { AdminPageHead, HelpNote } from '../AdminLayout';
import EmptyState from '../../components/EmptyState';
import ImageUploadButton from '../../components/ImageUploadButton';
import { formatMoney } from '../../utils/money';

const blank = { name:'', slug:'', sku:'', shortDescription:'', description:'', price:'', compareAtPrice:'', stock:0, status:'DRAFT', isFeatured:false, categoryId:'', brandId:'', images:[{url:'',altText:''}], collectionIds:[], variants:[], attributes:[], specifications:[], shippingInfo:{weightKg:'',lengthCm:'',breadthCm:'',heightCm:''}, metaTitle:'', metaDescription:'', canonicalUrl:'', ogImageUrl:'', noIndex:false };
const rows=(value)=>Object.entries(value||{}).map(([key,value])=>({key,value:String(value??'')}));
const objectFromRows=(items)=>Object.fromEntries((items||[]).filter((x)=>String(x.key||'').trim()).map((x)=>[String(x.key).trim(),x.value]));

export default function Products() {
  const [items,setItems]=useState([]); const [categories,setCategories]=useState([]); const [brands,setBrands]=useState([]); const [collections,setCollections]=useState([]); const [config,setConfig]=useState(null); const [search,setSearch]=useState(''); const [editing,setEditing]=useState(null); const [editorOpen,setEditorOpen]=useState(false); const [form,setForm]=useState(blank); const [state,setState]=useState({saving:false,error:''});
  async function load(){ const [p,c,b,col,cfg]=await Promise.all([get('/admin/products'),get('/admin/categories'),get('/admin/brands'),get('/admin/collections'),get('/admin/store-config')]); setItems(p);setCategories(c);setBrands(b);setCollections(col);setConfig(cfg); }
  useEffect(()=>{load();},[]);
  const filtered=useMemo(()=>items.filter((p)=>`${p.name} ${p.sku||''}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  function open(item=null){ setEditing(item); setEditorOpen(true); setState({saving:false,error:''}); setForm(item?{...blank,...item,price:Number(item.price),compareAtPrice:item.compareAtPrice?Number(item.compareAtPrice):'',categoryId:item.categoryId||'',brandId:item.brandId||'',images:item.images?.map((i)=>({url:i.url,altText:i.altText||''}))||[{url:'',altText:''}],collectionIds:item.collections?.map((c)=>c.collectionId)||[],attributes:rows(item.attributes),specifications:rows(item.specifications),shippingInfo:{...blank.shippingInfo,...(item.shippingInfo||{})},variants:(item.variants||[]).map((v)=>({...v,price:Number(v.price),compareAtPrice:v.compareAtPrice?Number(v.compareAtPrice):''}))}:blank); }
  async function save(e){e.preventDefault();setState({saving:true,error:''});try{const payload={...form,attributes:objectFromRows(form.attributes),specifications:objectFromRows(form.specifications),shippingInfo:Object.fromEntries(Object.entries(form.shippingInfo||{}).filter(([,v])=>String(v??'').trim()!=='')),price:Number(form.price||0),compareAtPrice:form.compareAtPrice===''?null:Number(form.compareAtPrice),stock:Number(form.stock||0),categoryId:form.categoryId||null,brandId:form.brandId||null,images:form.images.filter((image)=>image.url).map((image,index)=>({...image,sortOrder:index})),variants:form.variants.map((v)=>({...v,price:Number(v.price||0),compareAtPrice:v.compareAtPrice===''?null:Number(v.compareAtPrice),stock:Number(v.stock||0)}))}; if(editing)await put(`/admin/products/${editing.id}`,payload);else await post('/admin/products',payload);await load();setEditing(null);setEditorOpen(false);setForm(blank);}catch(error){setState({saving:false,error:error.message});}}
  async function del(item){if(!confirm(`Delete ${item.name}?`))return;try{await remove(`/admin/products/${item.id}`);load();}catch(e){alert(e.message)}}
  function variant(index,key,value){setForm({...form,variants:form.variants.map((v,i)=>i===index?{...v,[key]:value}:v)});}
  return <><AdminPageHead eyebrow="Catalog" title="Products" description="Create products in plain language. Add variants only when you need sizes, colors, weights or other options." action={<button className="button primary" onClick={()=>open()}><Plus size={17}/> Add product</button>}/><HelpNote>For a simple product, enter one price and stock quantity. Turn to variants only for products that have options such as size, color, storage or weight.</HelpNote><div className="admin-toolbar"><div className="input-with-icon"><Search size={17}/><input placeholder="Search products or SKU" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><span>{filtered.length} products</span></div>{filtered.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Status</th><th>Category</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody>{filtered.map((p)=><tr key={p.id}><td><div className="table-product"><div>{p.images?.[0]?.url?<img src={p.images[0].url} alt=""/>:<span/>}</div><div><strong>{p.name}</strong><small>{p.sku||'No SKU'}</small></div></div></td><td><span className={`status-pill ${p.status.toLowerCase()}`}>{p.status}</span></td><td>{p.category?.name||'—'}</td><td>{formatMoney(p.price,config)}</td><td>{p.variants?.length?p.variants.reduce((s,v)=>s+v.stock,0):p.stock}</td><td><div className="row-actions"><button onClick={()=>open(p)}><Edit3 size={16}/></button><button className="danger" onClick={()=>del(p)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState title="No products yet" text="Add your first product. You do not need to edit code." action={<button className="button primary" onClick={()=>open()}>Add product</button>}/>} {editorOpen && <div className="drawer-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget){setEditing(null);setEditorOpen(false);setForm(blank)}}}><aside className="editor-drawer"><div className="drawer-title"><div><span className="eyebrow">{editing?'Edit':'New'} product</span><h2>{editing?editing.name:'Add product'}</h2></div><button onClick={()=>{setEditing(null);setEditorOpen(false);setForm(blank)}}><X/></button></div><form onSubmit={save} className="drawer-form">
      <section><h3>Basic information</h3><label><span>Product name *</span><input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="What do you sell?"/></label><div className="two-fields"><label><span>SKU</span><input value={form.sku||''} onChange={(e)=>setForm({...form,sku:e.target.value})} placeholder="Optional stock code"/></label><label><span>Status</span><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label></div><label><span>Short description</span><textarea rows="2" value={form.shortDescription||''} onChange={(e)=>setForm({...form,shortDescription:e.target.value})} placeholder="One clear sentence for product cards"/></label><label><span>Full description</span><textarea rows="5" value={form.description||''} onChange={(e)=>setForm({...form,description:e.target.value})}/></label></section>
      <section><h3>Price & stock</h3><div className="three-fields"><label><span>Price *</span><input type="number" min="0" step="0.01" required value={form.price} onChange={(e)=>setForm({...form,price:e.target.value})}/></label><label><span>Compare price</span><input type="number" min="0" step="0.01" value={form.compareAtPrice||''} onChange={(e)=>setForm({...form,compareAtPrice:e.target.value})}/></label><label><span>Stock</span><input type="number" min="0" value={form.stock} onChange={(e)=>setForm({...form,stock:e.target.value})}/></label></div></section>
      <section><h3>Organization</h3><div className="two-fields"><label><span>Category</span><select value={form.categoryId} onChange={(e)=>setForm({...form,categoryId:e.target.value})}><option value="">No category</option>{categories.map((c)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label><span>Brand</span><select value={form.brandId} onChange={(e)=>setForm({...form,brandId:e.target.value})}><option value="">No brand</option>{brands.map((b)=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></div><label><span>Collections</span><div className="check-grid">{collections.map((c)=><label className="check-line" key={c.id}><input type="checkbox" checked={form.collectionIds.includes(c.id)} onChange={(e)=>setForm({...form,collectionIds:e.target.checked?[...form.collectionIds,c.id]:form.collectionIds.filter((id)=>id!==c.id)})}/>{c.name}</label>)}</div></label></section>
      <section><div className="section-row"><div><h3>Custom product information</h3><p>Add any fields your business needs. No database or code change is required.</p></div></div><span className="field-label">Attributes</span>{form.attributes.map((row,i)=><div className="inline-card" key={`a-${i}`}><input placeholder="Name e.g. Material" value={row.key} onChange={(e)=>setForm({...form,attributes:form.attributes.map((x,n)=>n===i?{...x,key:e.target.value}:x)})}/><input placeholder="Value e.g. Leather" value={row.value} onChange={(e)=>setForm({...form,attributes:form.attributes.map((x,n)=>n===i?{...x,value:e.target.value}:x)})}/><button type="button" onClick={()=>setForm({...form,attributes:form.attributes.filter((_,n)=>n!==i)})}>×</button></div>)}<button type="button" className="button secondary small" onClick={()=>setForm({...form,attributes:[...form.attributes,{key:'',value:''}]})}>+ Attribute</button><span className="field-label block-gap">Specifications</span>{form.specifications.map((row,i)=><div className="inline-card" key={`s-${i}`}><input placeholder="Name e.g. Storage" value={row.key} onChange={(e)=>setForm({...form,specifications:form.specifications.map((x,n)=>n===i?{...x,key:e.target.value}:x)})}/><input placeholder="Value e.g. 256 GB" value={row.value} onChange={(e)=>setForm({...form,specifications:form.specifications.map((x,n)=>n===i?{...x,value:e.target.value}:x)})}/><button type="button" onClick={()=>setForm({...form,specifications:form.specifications.filter((_,n)=>n!==i)})}>×</button></div>)}<button type="button" className="button secondary small" onClick={()=>setForm({...form,specifications:[...form.specifications,{key:'',value:''}]})}>+ Specification</button></section>
      <section><h3>Shipping package</h3><p>Optional per-product values. Shipping integrations use these before the store-wide defaults.</p><div className="four-fields"><label><span>Weight (kg)</span><input type="number" min="0" step="0.01" value={form.shippingInfo?.weightKg||''} onChange={(e)=>setForm({...form,shippingInfo:{...form.shippingInfo,weightKg:e.target.value}})}/></label><label><span>Length (cm)</span><input type="number" min="0" step="0.1" value={form.shippingInfo?.lengthCm||''} onChange={(e)=>setForm({...form,shippingInfo:{...form.shippingInfo,lengthCm:e.target.value}})}/></label><label><span>Width (cm)</span><input type="number" min="0" step="0.1" value={form.shippingInfo?.breadthCm||''} onChange={(e)=>setForm({...form,shippingInfo:{...form.shippingInfo,breadthCm:e.target.value}})}/></label><label><span>Height (cm)</span><input type="number" min="0" step="0.1" value={form.shippingInfo?.heightCm||''} onChange={(e)=>setForm({...form,shippingInfo:{...form.shippingInfo,heightCm:e.target.value}})}/></label></div></section>
      <section><div className="section-row"><div><h3>Images</h3><p>Upload an image from your device or paste an existing image URL.</p></div><div className="row-actions"><ImageUploadButton onUploaded={(url)=>setForm({...form,images:[...form.images.filter((image)=>image.url),{url,altText:form.name||''}]})}/><button type="button" className="button secondary small" onClick={()=>setForm({...form,images:[...form.images,{url:'',altText:''}]})}>+ URL</button></div></div>{form.images.map((image,i)=><div className="image-editor-row" key={i}><input value={image.url} onChange={(e)=>setForm({...form,images:form.images.map((x,n)=>n===i?{...x,url:e.target.value}:x)})} placeholder="Image URL"/><input value={image.altText||''} onChange={(e)=>setForm({...form,images:form.images.map((x,n)=>n===i?{...x,altText:e.target.value}:x)})} placeholder="SEO alt text / image description"/><button type="button" onClick={()=>setForm({...form,images:form.images.filter((_,n)=>n!==i)})}>×</button></div>)}</section>
      <section><div className="section-row"><div><h3>Variants</h3><p>Optional. Give each option combination its own SKU, price, stock and image.</p></div><button type="button" className="button secondary small" onClick={()=>setForm({...form,variants:[...form.variants,{title:'',sku:'',price:form.price||0,compareAtPrice:'',stock:0,imageUrl:'',options:{},isActive:true}]})}>+ Variant</button></div>{form.variants.map((v,i)=><div className="variant-card" key={v.id||i}><div className="variant-card-head"><strong>Option {i+1}</strong><label className="check-line"><input type="checkbox" checked={v.isActive!==false} onChange={(e)=>variant(i,'isActive',e.target.checked)}/> Available</label><button type="button" className="icon-button danger" onClick={()=>setForm({...form,variants:form.variants.filter((_,n)=>n!==i)})}>×</button></div><div className="two-fields"><label><span>Option label *</span><input required placeholder="Large / Blue, 1 kg, 256 GB…" value={v.title} onChange={(e)=>variant(i,'title',e.target.value)}/></label><label><span>SKU *</span><input required placeholder="Unique SKU" value={v.sku} onChange={(e)=>variant(i,'sku',e.target.value)}/></label></div><div className="three-fields"><label><span>Price</span><input type="number" min="0" step="0.01" value={v.price} onChange={(e)=>variant(i,'price',e.target.value)}/></label><label><span>Compare price</span><input type="number" min="0" step="0.01" value={v.compareAtPrice||''} onChange={(e)=>variant(i,'compareAtPrice',e.target.value)}/></label><label><span>Stock</span><input type="number" min="0" value={v.stock} onChange={(e)=>variant(i,'stock',e.target.value)}/></label></div><label><span>Variant image</span><div className="inline-field"><input value={v.imageUrl||''} onChange={(e)=>variant(i,'imageUrl',e.target.value)} placeholder="Optional image URL"/><ImageUploadButton onUploaded={(url)=>variant(i,'imageUrl',url)}/></div></label></div>)}</section>
      <section><h3>Search visibility</h3><label><span>SEO title</span><input value={form.metaTitle||''} onChange={(e)=>setForm({...form,metaTitle:e.target.value})} placeholder="Leave blank to use product name"/></label><label><span>Meta description</span><textarea rows="2" value={form.metaDescription||''} onChange={(e)=>setForm({...form,metaDescription:e.target.value})}/></label><div className="two-fields"><label><span>Canonical URL</span><input value={form.canonicalUrl||''} onChange={(e)=>setForm({...form,canonicalUrl:e.target.value})} placeholder="Optional canonical URL"/></label><label><span>Social share image</span><div className="inline-field"><input value={form.ogImageUrl||''} onChange={(e)=>setForm({...form,ogImageUrl:e.target.value})}/><ImageUploadButton onUploaded={(url)=>setForm({...form,ogImageUrl:url})}/></div></label></div><label className="check-line"><input type="checkbox" checked={Boolean(form.noIndex)} onChange={(e)=>setForm({...form,noIndex:e.target.checked})}/> Hide this product from search-engine indexing</label><label className="check-line"><input type="checkbox" checked={form.isFeatured} onChange={(e)=>setForm({...form,isFeatured:e.target.checked})}/> Feature this product on the storefront</label></section>
      {state.error&&<div className="alert error">{state.error}</div>}<div className="sticky-actions"><button type="button" className="button secondary" onClick={()=>{setEditing(null);setEditorOpen(false);setForm(blank)}}>Cancel</button><button className="button primary" disabled={state.saving}>{state.saving?'Saving…':'Save product'}</button></div>
    </form></aside></div>}
  </>;
}
